[template]
cargo_generate_version = ">=0.22.0"

[hooks]
pre = ["prehook_script.rhai"]

[placeholders]
project-pretty-name = { prompt = "Enter a user-facing name for the project", type = "string" }
rust-version = { prompt = "What is the minimum rust version for the project", type = "string", default = "1.80.0" }
