[template]
cargo_generate_version = ">=0.23.0"

[hooks]
pre = [
    "prehook_license.rhai",
    "prehook_manifest.rhai",
]
post = ["posthook_xtask.rhai"]

[placeholders.project-pretty-name]
prompt = "Enter a user-facing name for the project"
type = "string"

[placeholders.rust-version]
prompt = "What is the minimum rust version for the project?"
type = "string"
default = "1.86.0"

[placeholders.toplevel-crate]
prompt = "Please select the crate type of the top-level crate"
type = "string"
choices = [
    "none",
    "bin",
    "lib",
    "bin-and-lib",
]
default = "bin-and-lib"

[placeholders.include_xtask]
prompt = "Setup cargo xtask?"
type = "bool"
default = false

[conditional.'include_xtask == false']
ignore = ["tools", ".cargo"]
