[template]
cargo_generate_version = ">=0.23.0"

[hooks]
pre = [
    "prehook_license.rhai",
    "prehook_manifest.rhai",
]

[placeholders.rust-version]
prompt = "What is the minimum rust version for the project?"
type = "string"
default = "1.90.0"

[placeholders.toplevel_crate]
prompt = "Please select the crate type of the top-level crate"
type = "string"
choices = [
    "none",
    "bin",
    "lib",
    "bin-and-lib",
]
default = "bin-and-lib"

[placeholders.xtask]
prompt = "Include example xtask cargo script (requires nightly toolchain)?"
type = "bool"
default = false

[conditional.'xtask == false']
ignore = ["xtask.rs"]

[conditional.'toplevel_crate == "none"']
ignore = ["src"]

[conditional.'toplevel_crate == "bin"']
ignore = ["src/lib.rs"]

[conditional.'toplevel_crate == "lib"']
ignore = ["src/main.rs"]
